# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

dist: xenial

language: php

services:
  - postgresql

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install:
  - sudo locale-gen en_US.UTF-8
  - sudo locale-gen cs_CZ.UTF-8
  - sudo update-locale
  - locale -a
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - git submodule init && git submodule update
  - ./scripts/check_system || echo "FIX SYSTEM REQUIREMENTS!"

before_script:
  - echo "y" | ATK14_ENV=test ./scripts/create_database
  - echo "SELECT VERSION()" | ATK14_ENV=test ./scripts/dbconsole
  - ATK14_ENV=test ./scripts/migrate
  - echo '127.0.0.1 atk14embryo.localhost' | sudo tee --append /etc/hosts
  - ./scripts/check_installation || echo "FIX APPLICATION REQUIREMENTS!"

script:
  - ./scripts/run_all_tests && echo "EVERYTHING IS FINE"
