# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

addons:
  postgresql: "9.6"

jobs:
  include:
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: focal
      addons:
        postgresql: "12"
    - php: 8.0
      dist: focal
      addons:
        postgresql: "12"
    - php: 8.1
      dist: focal
      addons:
        postgresql: "12"
    - name: "PHP: 8.2"
      dist: jammy
      language: ruby
      addons:
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.2 php8.2-mbstring php8.2-cli php8.2-pgsql php8.2-readline php8.2-gd php8.2-xml
        - php -v
        - sudo apt-get install postgresql-16 postgresql-client-16
        - "sed -i 's/test:/test:\\n  port: 5433/' config/database.yml 2>&1"
    - name: "PHP: 8.3"
      dist: jammy
      language: ruby
      addons:
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.3 php8.3-mbstring php8.3-cli php8.3-pgsql php8.3-readline php8.3-gd php8.3-xml
        - php -v
        - sudo apt-get install postgresql-16 postgresql-client-16
        - "sed -i 's/test:/test:\\n  port: 5433/' config/database.yml 2>&1"

install:
  - sudo locale-gen en_US.UTF-8
  - sudo locale-gen cs_CZ.UTF-8
  - sudo update-locale
  - locale -a
  - git submodule init && git submodule update
  - ./scripts/check_system || echo "FIX SYSTEM REQUIREMENTS!"

# The phpunit/phpunit 7.5.20 package is compatible with PHP ^7.1 and also works on PHP 8.*
before_script:
  - travis_retry composer install --dev --no-interaction --prefer-dist
  - composer require --dev --ignore-platform-reqs "phpunit/phpunit=7.5.20" 2>&1
  - echo "y" | ATK14_ENV=test ./scripts/create_database 2>&1
  - echo "SELECT VERSION()" | ATK14_ENV=test ./scripts/dbconsole
  - ATK14_ENV=test ./scripts/migrate
  - echo '127.0.0.1 atk14skelet.localhost' | sudo tee --append /etc/hosts
  - ./scripts/check_installation || echo "FIX APPLICATION REQUIREMENTS!"

script:
  - ./scripts/run_all_tests && echo "EVERYTHING IS FINE"
