development:
  host: 127.0.0.1
  database: atk14embryo_devel
  username: atk14embryo_devel
  password: embryo

test:
  host: 127.0.0.1
  database: atk14embryo_test
  username: atk14embryo_test
  password: embryo

production:
  host: 127.0.0.1
  database: atk14embryo_production
  username: atk14embryo_production
  password: <?=sha1(SECRET_TOKEN."Very_Sophisticated_Production_Password_Hiding")?>
