# This is a recipe how to deploy this application to our production environment
#
# You can run the deployment process by typing
#  $ ./scripts/deploy production
#
# or just
#  $ ./scripts/deploy
#

production:
  url: "http://embryo.atk14.net/"
  server: "cloudkicker.plovarna.cz"                                           # we are deploying on this server
  user: "devel"                                                               # we are deploying as this user
  directory: "/home/{{user}}/apps/embryo.atk14.net/production/"               # in this directory is this application installed on the server
  deploy_repository: "{{user}}@{{server}}:apps/embryo.atk14.net/repos/production.git" # this is the URL of deployment git repository with a proper post-receive hook
  rsync: []
  after_deploy:
  - "./scripts/migrate && ./scripts/delete_temporary_files dbmole_cache"

# vim: et:ts=2
